services:
  gym-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/target
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/gymdb
      - SPRING_DATASOURCE_USERNAME=gymuser
      - SPRING_DATASOURCE_PASSWORD=gympassword
    depends_on:
      - postgres-db
  
  postgres-db:
    image: postgres:15
    container_name: gym_db_container
    environment:
      - POSTGRES_USER=gymuser
      - POSTGRES_PASSWORD=gympassword
      - POSTGRES_DB=gymdb
    ports:
      - "5432:5432"
    volumes:
      - gym_data:/var/lib/postgresql/data

volumes:
  gym_data: